Module: transfer_money.py 
Function: process_transfer 
Error: DataError(1406, "Data too long for column 'transaction_id' at row 1")